class BaseSettings:
    ### fields to autocomplete on settings
    PIPEDRIVE_DEALFLOW_API_TOKEN = None
    PIPEDRIVE_INVESTORS_API_TOKEN = None
    PIPEDRIVE_BASE_URL = None
    PIPEDRIVE_CONTACT_INVESTOR_CHOICES = None
    PIPEDRIVE_ORGANIZATION_INVESTOR_CHOICES = None
    PIPEDRIVE_ORGANIZATION_DEALFLOW_CHOICES = None
    PIPEDRIVE_CONTACT_DEALFLOW_CHOICES = None
    PIPEDRIVE_DEAL_INVESTOR_CHOICES = None
