country_list_sandbox: list = [
    {"id": 24, "label": "Afghanistan"},
    {"id": 25, "label": "Albania"},
    {"id": 26, "label": "Algeria"},
    {"id": 27, "label": "Andorra"},
    {"id": 28, "label": "Angola"},
    {"id": 29, "label": "Antigua and Barbuda"},
    {"id": 30, "label": "Argentina"},
    {"id": 31, "label": "Armenia"},
    {"id": 32, "label": "Australia"},
    {"id": 33, "label": "Austria"},
    {"id": 34, "label": "Azerbaijan"},
    {"id": 35, "label": "Bahamas"},
    {"id": 36, "label": "Bahrain"},
    {"id": 37, "label": "Bangladesh"},
    {"id": 38, "label": "Barbados"},
    {"id": 39, "label": "Belarus"},
    {"id": 40, "label": "Belgium"},
    {"id": 41, "label": "Belize"},
    {"id": 42, "label": "Benin"},
    {"id": 43, "label": "Bhutan"},
    {"id": 44, "label": "Bolivia"},
    {"id": 45, "label": "Bosnia and Herzegovina"},
    {"id": 46, "label": "Botswana"},
    {"id": 47, "label": "Brazil"},
    {"id": 48, "label": "Brunei"},
    {"id": 49, "label": "Bulgaria"},
    {"id": 50, "label": "Burkina Faso"},
    {"id": 51, "label": "Burundi"},
    {"id": 52, "label": "Cabo Verde"},
    {"id": 53, "label": "Cambodia"},
    {"id": 54, "label": "Cameroon"},
    {"id": 55, "label": "Canada"},
    {"id": 56, "label": "Central African Republic"},
    {"id": 57, "label": "Chad"},
    {"id": 58, "label": "Chile"},
    {"id": 59, "label": "China"},
    {"id": 60, "label": "Colombia"},
    {"id": 61, "label": "Comoros"},
    {"id": 62, "label": "Congo, Democratic Republic of the"},
    {"id": 63, "label": "Congo, Republic of the"},
    {"id": 64, "label": "Costa Rica"},
    {"id": 65, "label": "Croatia"},
    {"id": 66, "label": "Cuba"},
    {"id": 67, "label": "Cyprus"},
    {"id": 68, "label": "Czech Republic"},
    {"id": 69, "label": "Denmark"},
    {"id": 70, "label": "Djibouti"},
    {"id": 71, "label": "Dominica"},
    {"id": 72, "label": "Dominican Republic"},
    {"id": 73, "label": "East Timor"},
    {"id": 74, "label": "Ecuador"},
    {"id": 75, "label": "Egypt"},
    {"id": 76, "label": "El Salvador"},
    {"id": 77, "label": "Equatorial Guinea"},
    {"id": 78, "label": "Eritrea"},
    {"id": 79, "label": "Estonia"},
    {"id": 80, "label": "Eswatini (formerly Swaziland)"},
    {"id": 81, "label": "Ethiopia"},
    {"id": 82, "label": "Fiji"},
    {"id": 83, "label": "Finland"},
    {"id": 84, "label": "France"},
    {"id": 85, "label": "Gabon"},
    {"id": 86, "label": "Gambia"},
    {"id": 87, "label": "Georgia"},
    {"id": 88, "label": "Germany"},
    {"id": 89, "label": "Ghana"},
    {"id": 90, "label": "Greece"},
    {"id": 91, "label": "Grenada"},
    {"id": 92, "label": "Guatemala"},
    {"id": 93, "label": "Guinea"},
    {"id": 94, "label": "Guinea-Bissau"},
    {"id": 95, "label": "Guyana"},
    {"id": 96, "label": "Haiti"},
    {"id": 97, "label": "Honduras"},
    {"id": 98, "label": "Hungary"},
    {"id": 99, "label": "Iceland"},
    {"id": 100, "label": "India"},
    {"id": 101, "label": "Indonesia"},
    {"id": 102, "label": "Iran"},
    {"id": 103, "label": "Iraq"},
    {"id": 104, "label": "Ireland"},
    {"id": 105, "label": "Israel"},
    {"id": 106, "label": "Italy"},
    {"id": 107, "label": "Jamaica"},
    {"id": 108, "label": "Japan"},
    {"id": 109, "label": "Jordan"},
    {"id": 110, "label": "Kazakhstan"},
    {"id": 111, "label": "Kenya"},
    {"id": 112, "label": "Kiribati"},
    {"id": 113, "label": "Korea, North"},
    {"id": 114, "label": "Korea, South"},
    {"id": 115, "label": "Kosovo"},
    {"id": 116, "label": "Kuwait"},
    {"id": 117, "label": "Kyrgyzstan"},
    {"id": 118, "label": "Laos"},
    {"id": 119, "label": "Latvia"},
    {"id": 120, "label": "Lebanon"},
    {"id": 121, "label": "Lesotho"},
    {"id": 122, "label": "Liberia"},
    {"id": 123, "label": "Libya"},
    {"id": 124, "label": "Liechtenstein"},
    {"id": 125, "label": "Lithuania"},
    {"id": 126, "label": "Luxembourg"},
    {"id": 127, "label": "Madagascar"},
    {"id": 128, "label": "Malawi"},
    {"id": 129, "label": "Malaysia"},
    {"id": 130, "label": "Maldives"},
    {"id": 131, "label": "Mali"},
    {"id": 132, "label": "Malta"},
    {"id": 133, "label": "Marshall Islands"},
    {"id": 134, "label": "Mauritania"},
    {"id": 135, "label": "Mauritius"},
    {"id": 136, "label": "Mexico"},
    {"id": 137, "label": "Micronesia"},
    {"id": 138, "label": "Moldova"},
    {"id": 139, "label": "Monaco"},
    {"id": 140, "label": "Mongolia"},
    {"id": 141, "label": "Montenegro"},
    {"id": 142, "label": "Morocco"},
    {"id": 143, "label": "Mozambique"},
    {"id": 144, "label": "Myanmar (formerly Burma)"},
    {"id": 145, "label": "Namibia"},
    {"id": 146, "label": "Nauru"},
    {"id": 147, "label": "Nepal"},
    {"id": 148, "label": "Netherlands"},
    {"id": 149, "label": "New Zealand"},
    {"id": 150, "label": "Nicaragua"},
    {"id": 151, "label": "Niger"},
    {"id": 152, "label": "Nigeria"},
    {"id": 153, "label": "North Macedonia (formerly Macedonia)"},
    {"id": 154, "label": "Norway"},
    {"id": 155, "label": "Oman"},
    {"id": 156, "label": "Pakistan"},
    {"id": 157, "label": "Palau"},
    {"id": 158, "label": "Panama"},
    {"id": 159, "label": "Papua New Guinea"},
    {"id": 160, "label": "Paraguay"},
    {"id": 161, "label": "Peru"},
    {"id": 162, "label": "Qatar"},
    {"id": 163, "label": "Romania"},
    {"id": 164, "label": "Russia"},
    {"id": 165, "label": "Rwanda"},
    {"id": 166, "label": "Saint Kitts and Nevis"},
    {"id": 167, "label": "Saint Lucia"},
    {"id": 168, "label": "Saint Vincent and the Grenadines"},
    {"id": 169, "label": "Samoa"},
    {"id": 170, "label": "San Marino"},
    {"id": 171, "label": "Sao Tome and Principe"},
    {"id": 172, "label": "Saudi Arabia"},
    {"id": 173, "label": "Senegal"},
    {"id": 174, "label": "Serbia"},
    {"id": 175, "label": "Seychelles"},
    {"id": 176, "label": "Sierra Leone"},
    {"id": 177, "label": "Singapore"},
    {"id": 178, "label": "Slovakia"},
    {"id": 179, "label": "Slovenia"},
    {"id": 180, "label": "Solomon Islands"},
    {"id": 181, "label": "Somalia"},
    {"id": 182, "label": "South Africa"},
    {"id": 183, "label": "South Sudan"},
    {"id": 184, "label": "Spain"},
    {"id": 185, "label": "Sri Lanka"},
    {"id": 186, "label": "Sudan"},
    {"id": 187, "label": "Suriname"},
    {"id": 188, "label": "Sweden"},
    {"id": 189, "label": "Switzerland"},
    {"id": 190, "label": "Syria"},
    {"id": 191, "label": "Taiwan"},
    {"id": 192, "label": "Tajikistan"},
    {"id": 193, "label": "Tanzania"},
    {"id": 194, "label": "Thailand"},
    {"id": 195, "label": "Togo"},
    {"id": 196, "label": "Tonga"},
    {"id": 197, "label": "Trinidad and Tobago"},
    {"id": 198, "label": "Tunisia"},
    {"id": 199, "label": "Turkey"},
    {"id": 200, "label": "Turkmenistan"},
    {"id": 201, "label": "Tuvalu"},
    {"id": 202, "label": "Uganda"},
    {"id": 203, "label": "Ukraine"},
    {"id": 204, "label": "United Arab Emirates"},
    {"id": 205, "label": "United Kingdom"},
    {"id": 206, "label": "United States of America"},
    {"id": 207, "label": "Uruguay"},
    {"id": 208, "label": "Uzbekistan"},
    {"id": 209, "label": "Vanuatu"},
    {"id": 210, "label": "Vatican City (Holy See)"},
    {"id": 211, "label": "Venezuela"},
    {"id": 212, "label": "Vietnam"},
    {"id": 213, "label": "Yemen"},
    {"id": 214, "label": "Zambia"},
    {"id": 215, "label": "Zimbabwe"},
]

country_list_prod: list = [
    {"id": 20, "label": "Afghanistan"},
    {"id": 21, "label": "Albania"},
    {"id": 22, "label": "Algeria"},
    {"id": 23, "label": "Andorra"},
    {"id": 24, "label": "Angola"},
    {"id": 25, "label": "Antigua and Barbuda"},
    {"id": 26, "label": "Argentina"},
    {"id": 27, "label": "Armenia"},
    {"id": 28, "label": "Australia"},
    {"id": 29, "label": "Austria"},
    {"id": 30, "label": "Azerbaijan"},
    {"id": 31, "label": "Bahamas"},
    {"id": 32, "label": "Bahrain"},
    {"id": 33, "label": "Bangladesh"},
    {"id": 34, "label": "Barbados"},
    {"id": 35, "label": "Belarus"},
    {"id": 36, "label": "Belgium"},
    {"id": 37, "label": "Belize"},
    {"id": 38, "label": "Benin"},
    {"id": 39, "label": "Bhutan"},
    {"id": 40, "label": "Bolivia"},
    {"id": 41, "label": "Bosnia and Herzegovina"},
    {"id": 42, "label": "Botswana"},
    {"id": 43, "label": "Brazil"},
    {"id": 44, "label": "Brunei"},
    {"id": 45, "label": "Bulgaria"},
    {"id": 46, "label": "Burkina Faso"},
    {"id": 47, "label": "Burundi"},
    {"id": 48, "label": "Cabo Verde"},
    {"id": 49, "label": "Cambodia"},
    {"id": 50, "label": "Cameroon"},
    {"id": 51, "label": "Canada"},
    {"id": 52, "label": "Central African Republic"},
    {"id": 53, "label": "Chad"},
    {"id": 54, "label": "Chile"},
    {"id": 55, "label": "China"},
    {"id": 56, "label": "Colombia"},
    {"id": 57, "label": "Comoros"},
    {"id": 58, "label": "Congo, Democratic Republic of the"},
    {"id": 59, "label": "Congo, Republic of the"},
    {"id": 60, "label": "Costa Rica"},
    {"id": 61, "label": "Croatia"},
    {"id": 62, "label": "Cuba"},
    {"id": 63, "label": "Cyprus"},
    {"id": 64, "label": "Czech Republic"},
    {"id": 65, "label": "Denmark"},
    {"id": 66, "label": "Djibouti"},
    {"id": 67, "label": "Dominica"},
    {"id": 68, "label": "Dominican Republic"},
    {"id": 69, "label": "East Timor (Timor-Leste)"},
    {"id": 70, "label": "Ecuador"},
    {"id": 71, "label": "Egypt"},
    {"id": 72, "label": "El Salvador"},
    {"id": 73, "label": "Equatorial Guinea"},
    {"id": 74, "label": "Eritrea"},
    {"id": 75, "label": "Estonia"},
    {"id": 76, "label": "Eswatini (formerly Swaziland)"},
    {"id": 77, "label": "Ethiopia"},
    {"id": 78, "label": "Fiji"},
    {"id": 79, "label": "Finland"},
    {"id": 80, "label": "France"},
    {"id": 81, "label": "Gabon"},
    {"id": 82, "label": "Gambia"},
    {"id": 83, "label": "Georgia"},
    {"id": 84, "label": "Germany"},
    {"id": 85, "label": "Ghana"},
    {"id": 86, "label": "Greece"},
    {"id": 87, "label": "Grenada"},
    {"id": 88, "label": "Guatemala"},
    {"id": 89, "label": "Guinea"},
    {"id": 90, "label": "Guinea-Bissau"},
    {"id": 91, "label": "Guyana"},
    {"id": 92, "label": "Haiti"},
    {"id": 93, "label": "Honduras"},
    {"id": 94, "label": "Hungary"},
    {"id": 95, "label": "Iceland"},
    {"id": 96, "label": "India"},
    {"id": 97, "label": "Indonesia"},
    {"id": 98, "label": "Iran"},
    {"id": 99, "label": "Iraq"},
    {"id": 100, "label": "Ireland"},
    {"id": 101, "label": "Israel"},
    {"id": 102, "label": "Italy"},
    {"id": 103, "label": "Jamaica"},
    {"id": 104, "label": "Japan"},
    {"id": 105, "label": "Jordan"},
    {"id": 106, "label": "Kazakhstan"},
    {"id": 107, "label": "Kenya"},
    {"id": 108, "label": "Kiribati"},
    {"id": 109, "label": "Korea, North"},
    {"id": 110, "label": "Korea, South"},
    {"id": 111, "label": "Kosovo"},
    {"id": 112, "label": "Kuwait"},
    {"id": 113, "label": "Kyrgyzstan"},
    {"id": 114, "label": "Laos"},
    {"id": 115, "label": "Latvia"},
    {"id": 116, "label": "Lebanon"},
    {"id": 117, "label": "Lesotho"},
    {"id": 118, "label": "Liberia"},
    {"id": 119, "label": "Libya"},
    {"id": 120, "label": "Liechtenstein"},
    {"id": 121, "label": "Lithuania"},
    {"id": 122, "label": "Luxembourg"},
    {"id": 123, "label": "Madagascar"},
    {"id": 124, "label": "Malawi"},
    {"id": 125, "label": "Malaysia"},
    {"id": 126, "label": "Maldives"},
    {"id": 127, "label": "Mali"},
    {"id": 128, "label": "Malta"},
    {"id": 129, "label": "Marshall Islands"},
    {"id": 130, "label": "Mauritania"},
    {"id": 131, "label": "Mauritius"},
    {"id": 132, "label": "Mexico"},
    {"id": 133, "label": "Micronesia"},
    {"id": 134, "label": "Moldova"},
    {"id": 135, "label": "Monaco"},
    {"id": 136, "label": "Mongolia"},
    {"id": 137, "label": "Montenegro"},
    {"id": 138, "label": "Morocco"},
    {"id": 139, "label": "Mozambique"},
    {"id": 140, "label": "Myanmar (formerly Burma)"},
    {"id": 141, "label": "Namibia"},
    {"id": 142, "label": "Nauru"},
    {"id": 143, "label": "Nepal"},
    {"id": 144, "label": "Netherlands"},
    {"id": 145, "label": "New Zealand"},
    {"id": 146, "label": "Nicaragua"},
    {"id": 147, "label": "Niger"},
    {"id": 148, "label": "Nigeria"},
    {"id": 149, "label": "North Macedonia (formerly Macedonia)"},
    {"id": 150, "label": "Norway"},
    {"id": 151, "label": "Oman"},
    {"id": 152, "label": "Pakistan"},
    {"id": 153, "label": "Palau"},
    {"id": 154, "label": "Palestine, State of"},
    {"id": 155, "label": "Panama"},
    {"id": 156, "label": "Papua New Guinea"},
    {"id": 157, "label": "Paraguay"},
    {"id": 158, "label": "Peru"},
    {"id": 159, "label": "Philippines"},
    {"id": 160, "label": "Poland"},
    {"id": 161, "label": "Portugal"},
    {"id": 162, "label": "Qatar"},
    {"id": 163, "label": "Romania"},
    {"id": 164, "label": "Russia"},
    {"id": 165, "label": "Rwanda"},
    {"id": 166, "label": "Saint Kitts and Nevis"},
    {"id": 167, "label": "Saint Lucia"},
    {"id": 168, "label": "Saint Vincent and the Grenadines"},
    {"id": 169, "label": "Samoa"},
    {"id": 170, "label": "San Marino"},
    {"id": 171, "label": "Sao Tome and Principe"},
    {"id": 172, "label": "Saudi Arabia"},
    {"id": 173, "label": "Senegal"},
    {"id": 174, "label": "Serbia"},
    {"id": 175, "label": "Seychelles"},
    {"id": 176, "label": "Sierra Leone"},
    {"id": 177, "label": "Singapore"},
    {"id": 178, "label": "Slovakia"},
    {"id": 179, "label": "Slovenia"},
    {"id": 180, "label": "Solomon Islands"},
    {"id": 181, "label": "Somalia"},
    {"id": 182, "label": "South Africa"},
    {"id": 183, "label": "South Sudan"},
    {"id": 184, "label": "Spain"},
    {"id": 185, "label": "Sri Lanka"},
    {"id": 186, "label": "Sudan"},
    {"id": 187, "label": "Suriname"},
    {"id": 188, "label": "Sweden"},
    {"id": 189, "label": "Switzerland"},
    {"id": 190, "label": "Syria"},
    {"id": 191, "label": "Taiwan"},
    {"id": 192, "label": "Tajikistan"},
    {"id": 193, "label": "Tanzania"},
    {"id": 194, "label": "Thailand"},
    {"id": 195, "label": "Togo"},
    {"id": 196, "label": "Tonga"},
    {"id": 197, "label": "Trinidad and Tobago"},
    {"id": 198, "label": "Tunisia"},
    {"id": 199, "label": "Turkey"},
    {"id": 200, "label": "Turkmenistan"},
    {"id": 201, "label": "Tuvalu"},
    {"id": 202, "label": "Uganda"},
    {"id": 203, "label": "Ukraine"},
    {"id": 204, "label": "United Arab Emirates"},
    {"id": 205, "label": "United Kingdom"},
    {"id": 206, "label": "United States"},
    {"id": 207, "label": "Uruguay"},
    {"id": 208, "label": "Uzbekistan"},
    {"id": 209, "label": "Vanuatu"},
    {"id": 210, "label": "Vatican City"},
    {"id": 211, "label": "Venezuela"},
    {"id": 212, "label": "Vietnam"},
    {"id": 213, "label": "Yemen"},
    {"id": 214, "label": "Zambia"},
    {"id": 215, "label": "Zimbabwe"},
]

language_list_sandbox: list = [
    {"id": 20, "label": "FR"},
    {"id": 21, "label": "Spanish"},
    {"id": 22, "label": "EN"},
    {"id": 23, "label": "Italian"},
]

language_list_prod: list = [
    {"id": 216, "label": "FR"},
    {"id": 217, "label": "Spanish"},
    {"id": 218, "label": "EN"},
    {"id": 219, "label": "Italian"},
]
source_options_sandbox: list = [
    {"id": 216, "label": "Community network"},
    {"id": 217, "label": "Women in VC"},
    {"id": 218, "label": "Prospection"},
    {"id": 219, "label": "Stéphanie network"},
    {"id": 220, "label": "Co-investor"},
    {"id": 221, "label": "DeepDive"},
    {"id": 222, "label": "Events"},
    {"id": 223, "label": "Platform inbound "},
    {"id": 407, "label": "Core"},
    {"id": 422, "label": "LinkedIn Sales Navigator"},
    {"id": 431, "label": "Prospection Bas"},
    {"id": 432, "label": "Remploi"},
    {"id": 433, "label": "Contacts JMM"},
    {"id": 434, "label": "Institutional Prospection"},
    {"id": 435, "label": "Prospection FO/MFO"},
]

source_options_prod: list = [
    {"id": 222, "label": "Community network"},
    {"id": 223, "label": "Women in VC"},
    {"id": 224, "label": "Prospection"},
    {"id": 225, "label": "Stéphanie network"},
    {"id": 226, "label": "Co-investor"},
    {"id": 227, "label": "DeepDive"},
    {"id": 228, "label": "Events"},
    {"id": 229, "label": "Platform inbound "},
    {"id": 262, "label": "Core"},
    {"id": 353, "label": "LinkedIn Sales Navigator"},
]

sub_source_options_sandbox: list = [
    {"id": 224, "label": "[Prospection] 150-OB-ter"},
    {"id": 225, "label": "[Prospection] Courtier/Assureurs. "},
    {"id": 226, "label": "[Events] MWC2023"},
    {"id": 227, "label": "[Events] SouthSummit2023"},
    {"id": 228, "label": "[Platform inbound] From the press "},
    {"id": 229, "label": "[Platform inbound] From BFM"},
    {"id": 230, "label": "[Co- investors] Shotgun"},
    {
        "id": 424,
        "label": "[LSN] 20 - DeepDive - April 23 - SalesNav Investor - Profile Scraper",
    },
]

sub_source_options_prod: list = [
    {"id": 230, "label": "[Prospection] 150-OB-ter"},
    {"id": 231, "label": "[Prospection] Courtier/Assureurs. "},
    {"id": 232, "label": "[Events] MWC2023"},
    {"id": 233, "label": "[Events] SouthSummit2023"},
    {"id": 234, "label": "[Platform inbound] From the press "},
    {"id": 235, "label": "[Platform inbound] From BFM"},
    {"id": 236, "label": "[Co- investors] Shotgun"},
    {
        "id": 354,
        "label": "[LSN] 20 - DeepDive - April 23 - SalesNav Investor - Profile Scraper",
    },
]

tu_vous_options_sandbox: list = [
    {"id": 405, "label": "Tu"},
    {"id": 406, "label": "Vous"},
]
tu_vous_options_prod: list = [{"id": 220, "label": "Tu"}, {"id": 221, "label": "Vous"}]

newsletter_options_sandbox: list = [
    {"id": 231, "label": "yes"},
    {"id": 232, "label": "no"},
]
newsletter_options_prod: list = [
    {"id": 237, "label": "yes"},
    {"id": 238, "label": "no"},
]
category_options_sandbox: list = [
    {"id": 233, "label": "Main(s) contact(s)"},
    {"id": 234, "label": "Assistant"},
    {"id": 235, "label": "Employee"},
]

category_options_prod: list = [
    {"id": 17, "label": "Main(s) contact(s)"},
    {"id": 18, "label": "Assistant"},
    {"id": 19, "label": "Employee"},
]

organization_type_list_options_sandbox: list = [
    {"id": 256, "label": "Investor"},
    {"id": 257, "label": "Partner"},
    {"id": 421, "label": "Private bank"},
]

organization_type_list_options_prod: list = [
    {"id": 239, "label": "Investor"},
    {"id": 240, "label": "Partner"},
    {"id": 348, "label": "Private bank"},
]

organization_qualification_list_options_sandbox: list = [
    {"label": "Private", "id": 252},
    {"label": "Institucional", "id": 253},
    {"label": "Referecement", "id": 254},
    {"label": "Distribution", "id": 255},
]

organization_qualification_list_options_prod: list = [
    {"id": 256, "label": "Private"},
    {"id": 257, "label": "Institutional"},
    {"id": 258, "label": "Referencement"},
    {"id": 259, "label": "Distribution"},
]

organization_category_list_options_sandbox: list = [
    {"id": 236, "label": "Legal"},
    {"id": 237, "label": "Individual"},
    {"id": 238, "label": "FO"},
    {"id": 239, "label": "MFO"},
    {"id": 240, "label": "Insurance"},
    {"id": 241, "label": "Bank"},
    {"id": 242, "label": "Private Bank"},
    {"id": 243, "label": "Regional fund"},
    {"id": 244, "label": "Pension Fund"},
    {"id": 245, "label": "CGP"},
    {"id": 246, "label": "Coporate"},
    {"id": 247, "label": "Corporate"},
    {"id": 248, "label": "Sovereign wealth fund"},
    {"id": 249, "label": "CVC"},
    {"id": 250, "label": "Fund of Fund"},
    {"id": 251, "label": "Fundraiser"},
    {"id": 408, "label": "Main(s) contact(s)"},
    {"id": 429, "label": "Institutional"},
]
organization_category_list_options_prod: list = [
    {"id": 241, "label": "Legal"},
    {"id": 242, "label": "Individual"},
    {"id": 243, "label": "family_office"},
    {"id": 244, "label": "multi_family_office"},
    {"id": 245, "label": "Insurance"},
    {"id": 246, "label": "[Investor] Bank"},
    {"id": 247, "label": "[Partner] Private Bank"},
    {"id": 248, "label": "[Investor] Regional fund"},
    {"id": 249, "label": "[Investor] Pension fund"},
    {"id": 250, "label": "[Partner] CGP"},
    {"id": 251, "label": "[Investor] Corporate"},
    {"id": 252, "label": "[Investor] Sovereign wealth fund"},
    {"id": 253, "label": "[Investor] CVC"},
    {"id": 254, "label": "[Investor] Fund of Fund"},
    {"id": 255, "label": "[Partner] Fundraiser"},
    {"id": 347, "label": "Main(s) contact(s)"},
    {"id": 358, "label": "Institutional"},
]

activity_type_list: list = [
    {
        "id": 1,
        "order_nr": 1,
        "name": "Call",
        "key_string": "call",
        "icon_key": "call",
        "active_flag": True,
        "color": None,
        "is_custom_flag": False,
        "add_time": "2023-06-21 09:50:11",
        "update_time": None,
    },
    {
        "id": 2,
        "order_nr": 2,
        "name": "Meeting",
        "key_string": "meeting",
        "icon_key": "meeting",
        "active_flag": True,
        "color": None,
        "is_custom_flag": False,
        "add_time": "2023-06-21 09:50:11",
        "update_time": None,
    },
    {
        "id": 3,
        "order_nr": 3,
        "name": "Task",
        "key_string": "task",
        "icon_key": "task",
        "active_flag": True,
        "color": None,
        "is_custom_flag": False,
        "add_time": "2023-06-21 09:50:11",
        "update_time": None,
    },
    {
        "id": 4,
        "order_nr": 4,
        "name": "Deadline",
        "key_string": "deadline",
        "icon_key": "deadline",
        "active_flag": True,
        "color": None,
        "is_custom_flag": False,
        "add_time": "2023-06-21 09:50:11",
        "update_time": None,
    },
    {
        "id": 5,
        "order_nr": 5,
        "name": "Email",
        "key_string": "email",
        "icon_key": "email",
        "active_flag": True,
        "color": None,
        "is_custom_flag": False,
        "add_time": "2023-06-21 09:50:11",
        "update_time": None,
    },
    {
        "id": 6,
        "order_nr": 6,
        "name": "Lunch",
        "key_string": "lunch",
        "icon_key": "lunch",
        "active_flag": True,
        "color": None,
        "is_custom_flag": False,
        "add_time": "2023-06-21 09:50:11",
        "update_time": None,
    },
]


fundraising_list_choices_sandbox: list = [
    {"id": 16, "label": "Sonio Seed"},
    {"id": 17, "label": "Studytrack series a"},
    {"id": 18, "label": "Studytrack series B"},
    {"id": 19, "label": "Studytrack seed"},
    {"id": 335, "label": "Keli Network Seed 2017 #3"},
    {"id": 336, "label": "Zenly Series B 2017 #2"},
    {"id": 337, "label": "Gestoos Seed 2017 #2"},
    {"id": 338, "label": "+Simple.fr Seed 2017 #3"},
    {"id": 339, "label": "Marie Quantier Seed 2018 #2"},
    {"id": 340, "label": "Make.org Series A 2018 #2"},
    {"id": 341, "label": "onoff Series A 2018 #2"},
    {"id": 342, "label": "+Simple.fr Series A 2018 #3"},
    {"id": 343, "label": "Keli Network Series A 2018 #3"},
    {"id": 344, "label": "MATCHTUNE Seed 2018 #2"},
    {"id": 345, "label": "Glose-fundraising"},
    {"id": 346, "label": "PhantomBuster"},
    {"id": 347, "label": "Woleet Seed 2018 #2"},
    {"id": 348, "label": "Hoomano-Fundraising"},
    {"id": 349, "label": "Antescofo"},
    {"id": 350, "label": "ExactCure-Fundraising"},
    {"id": 351, "label": "onoff Bridge 2019"},
    {"id": 352, "label": "Studytracks"},
    {"id": 353, "label": "Loopsider-Fundraising"},
    {"id": 354, "label": "Zyl Seed 2019 #1"},
    {"id": 355, "label": "OneRagtime Rhapsody I"},
    {"id": 356, "label": "Make.org Bridge"},
    {"id": 357, "label": "Yogosha Seed 2019 #1"},
    {"id": 358, "label": "Woonivers Seed 2019 #1"},
    {"id": 359, "label": "Zar Seed 2019 #1"},
    {"id": 360, "label": "Homa Games Series A 2019 #1"},
    {"id": 361, "label": "+Simple.fr Series B 2020 #3"},
    {"id": 362, "label": "Buster.AI Seed 2020 #1"},
    {"id": 363, "label": "Fintel Seed 2020 #1"},
    {"id": 364, "label": 'Yogosha Bridge 2020 #2",'},
    {"id": 365, "label": "WeLink Series A 2020 #1"},
    {"id": 366, "label": "Avostart Seed 2020 #1"},
    {"id": 367, "label": "Golem.ai Series A 2020 #1"},
    {"id": 368, "label": "Albums Seed 2020 #1"},
    {"id": 369, "label": "Choose Series A 2020 #2"},
    {"id": 370, "label": "Homa Games Bridge 2021 #2"},
    {"id": 371, "label": "Mantra Seed 2021 #1"},
    {"id": 372, "label": "Mayane Labs Seed 2021 #1"},
    {"id": 373, "label": "Aster Seed 2021 #1"},
    {"id": 374, "label": "WeLink Bridge 2021 #3"},
    {"id": 375, "label": "Studytracks Seed 2021 #2"},
    {"id": 376, "label": "Navee Seed 2021 #1"},
    {"id": 377, "label": "Gestoos Bridge 2021 #3"},
    {"id": 378, "label": "Staycation Series A 2021 #1"},
    {"id": 379, "label": "Hellosafe Seed 2021 #1"},
    {"id": 380, "label": "WeLink Series B 2021 #6"},
    {"id": 381, "label": "Yogosha Bridge 2021 #3"},
    {"id": 382, "label": "Yogosha Series A 2021 #5"},
    {"id": 383, "label": "MATCHTUNE Series A (US) 2021 #2"},
    {"id": 384, "label": "MATCHTUNE Series A (FR) 2021 #3"},
    {"id": 385, "label": "Benefiz Seed 2022 #1"},
    {"id": 386, "label": "Shotgun Series A 2022 #1"},
    {"id": 387, "label": "Make.org Bridge 2022 #5"},
    {"id": 388, "label": "Hive Seed 2022 #2"},
    {"id": 389, "label": "Choose Bridge 2022 #4"},
    {"id": 390, "label": "LoneScale Seed 2022 #1"},
    {"id": 391, "label": "Sonio Seed 2022 #3"},
    {"id": 392, "label": "Homa Games Series BB 2022 #4"},
    {"id": 393, "label": "Zar Pre-series A 2022 #2"},
    {"id": 394, "label": "Mayane Labs Series A 2022 #3"},
    {"id": 395, "label": "Medium Growth 2022 #1"},
    {"id": 396, "label": "Captain Cause Seed 2022 #1"},
    {"id": 397, "label": "Pickme Seed 2022 #1"},
    {"id": 398, "label": "Jellysmack Ideation 2016"},
    {"id": 399, "label": "Aster Series A 2022 #2"},
    {"id": 400, "label": "Jellysmack SAS Series C 2022 #1"},
    {"id": 401, "label": "MatchTune SAS Series A 2022 #1"},
    {"id": 402, "label": "Golem.ai Bridge 2023 #2"},
    {"id": 403, "label": "Hive Bridge 2023 #2"},
    {"id": 404, "label": "Motion Society Seed #"},
    {"id": 409, "label": "Homa Games Series B 2021 #3"},
    {"id": 410, "label": "Staycation Series A 2021 #1"},
    {"id": 411, "label": "OneRagtime Rhapsody II"},
    {"id": 412, "label": "Choose Series B 2023 #5"},
    {"id": 413, "label": "OneRagtime Paragon"},
    {"id": 414, "label": "Hoomano Pre-series A 2023 #2"},
    {"id": 415, "label": "Motion Society Seed #1"},
    {"id": 416, "label": "Stokelp Seed 2023 #1"},
    {"id": 417, "label": "LoneScale pre-series A 2023 #2"},
    {"id": 418, "label": "Sonio Series A 2023 #2"},
    {"id": 419, "label": "Estaly Seed 2023 #1"},
    {"id": 420, "label": "Groover Series A 2023 #2"},
    {"id": 425, "label": "Guzman-Chambers"},
    {"id": 426, "label": "Lee, Mills and Skinner"},
    {"id": 427, "label": "Quinn-Robinson"},
    {"id": 430, "label": "Golem.ai Bridge 2023 #3"},
    {"id": 436, "label": "OneRagtime Collective 2023 #1"},
    {"id": 437, "label": "Hive Series A 2023 #3"},
]

fundraising_list_choices_prod: list = [
    {"id": 264, "label": "Keli Network Seed 2017 #3"},
    {"id": 265, "label": "Zenly Series B 2017 #2"},
    {"id": 266, "label": "Gestoos Seed 2017 #2"},
    {"id": 267, "label": "+Simple.fr Seed 2017 #3"},
    {"id": 268, "label": "Marie Quantier Seed 2018 #2"},
    {"id": 269, "label": "Make.org Series A 2018 #2"},
    {"id": 270, "label": "onoff Series A 2018 #2"},
    {"id": 271, "label": "+Simple.fr Series A 2018 #3"},
    {"id": 272, "label": "Keli Network Series A 2018 #3"},
    {"id": 273, "label": "MATCHTUNE Seed 2018 #2"},
    {"id": 274, "label": "Glose-fundraising"},
    {"id": 275, "label": "PhantomBuster"},
    {"id": 276, "label": "Woleet Seed 2018 #2"},
    {"id": 277, "label": "Hoomano-Fundraising"},
    {"id": 278, "label": "Antescofo"},
    {"id": 279, "label": "ExactCure-Fundraising"},
    {"id": 280, "label": "onoff Bridge 2019"},
    {"id": 281, "label": "Studytracks"},
    {"id": 282, "label": "Loopsider-Fundraising"},
    {"id": 283, "label": "Zyl Seed 2019 #1"},
    {"id": 284, "label": "OneRagtime Rhapsody I"},
    {"id": 285, "label": "Make.org Bridge"},
    {"id": 286, "label": "Yogosha Seed 2019 #1"},
    {"id": 287, "label": "Woonivers Seed 2019 #1"},
    {"id": 288, "label": "Zar Seed 2019 #1"},
    {"id": 289, "label": "Homa Games Series A 2019 #1"},
    {"id": 290, "label": "+Simple.fr Series B 2020 #3"},
    {"id": 291, "label": "Buster.AI Seed 2020 #1"},
    {"id": 292, "label": "Fintel Seed 2020 #1"},
    {"id": 293, "label": "Yogosha Bridge 2020 #2"},
    {"id": 294, "label": "WeLink Series A 2020 #1"},
    {"id": 295, "label": "Avostart Seed 2020 #1"},
    {"id": 296, "label": "Golem.ai Series A 2020 #1"},
    {"id": 297, "label": "Albums Seed 2020 #1"},
    {"id": 298, "label": "Choose Series A 2020 #2"},
    {"id": 299, "label": "Homa Games Bridge 2021 #2"},
    {"id": 300, "label": "Mantra Seed 2021 #1"},
    {"id": 301, "label": "Mayane Labs Seed 2021 #1"},
    {"id": 302, "label": "Aster Seed 2021 #1"},
    {"id": 303, "label": "WeLink Bridge 2021 #3"},
    {"id": 304, "label": "Studytracks Seed 2021 #2"},
    {"id": 305, "label": "Navee Seed 2021 #1"},
    {"id": 306, "label": "Gestoos Bridge 2021 #3"},
    {"id": 307, "label": "Staycation Series A 2021 #1"},
    {"id": 308, "label": "Homa Games Series B 2021 #3"},
    {"id": 309, "label": "Hellosafe Seed 2021 #1"},
    {"id": 310, "label": "WeLink Series B 2021 #6"},
    {"id": 311, "label": "Yogosha Bridge 2021 #3"},
    {"id": 312, "label": "Yogosha Series A 2021 #5"},
    {"id": 313, "label": "MATCHTUNE Series A (US) 2021 #2"},
    {"id": 314, "label": "MATCHTUNE Series A (FR) 2021 #3"},
    {"id": 315, "label": "Benefiz Seed 2022 #1"},
    {"id": 316, "label": "Shotgun Series A 2022 #1"},
    {"id": 317, "label": "Make.org Bridge 2022 #5"},
    {"id": 318, "label": "Hive Seed 2022 #2"},
    {"id": 319, "label": "Choose Bridge 2022 #4"},
    {"id": 320, "label": "LoneScale Seed 2022 #1"},
    {"id": 321, "label": "Sonio Seed 2022 #3"},
    {"id": 322, "label": "Homa Games Series BB 2022 #4"},
    {"id": 323, "label": "Zar Pre-series A 2022 #2"},
    {"id": 324, "label": "Mayane Labs Series A 2022 #3"},
    {"id": 325, "label": "Medium Growth 2022 #1"},
    {"id": 326, "label": "Captain Cause Seed 2022 #1"},
    {"id": 327, "label": "Pickme Seed 2022 #1"},
    {"id": 328, "label": "Jellysmack Ideation 2016"},
    {"id": 329, "label": "Aster Series A 2022 #2"},
    {"id": 330, "label": "Jellysmack SAS Series C 2022 #1"},
    {"id": 331, "label": "MatchTune SAS Series A 2022 #1"},
    {"id": 332, "label": "Golem.ai Bridge 2023 #2"},
    {"id": 333, "label": "Hive Bridge 2023 #2"},
    {"id": 334, "label": "Motion Society Seed #1"},
    {"id": 335, "label": "Medium Growth 2022 #1"},
    {"id": 336, "label": "Hoomano Pre-series A 2023 #2"},
    {"id": 337, "label": "Estaly Seed 2023 #1"},
    {"id": 338, "label": "Sonio Series A 2023 #2"},
    {"id": 339, "label": "OneRagtime Paragon"},
    {"id": 340, "label": "MATCHTUNE Series A (FR) 2021 #3"},
    {"id": 341, "label": "Stokelp Seed 2023 #1"},
    {"id": 342, "label": "OneRagtime Rhapsody II"},
    {"id": 343, "label": "LoneScale pre-series A 2023 #2"},
    {"id": 344, "label": "Groover Series A 2023 #2"},
    {"id": 345, "label": "Zenly Series B 2017 #2"},
    {"id": 346, "label": "Choose Series B 2023 #5"},
    {"id": 355, "label": "Woonivers Relance (Sipay) 2023 "},
    {"id": 360, "label": "Golem.ai Bridge 2023 #3"},
    {"id": 366, "label": "OneRagtime Collective 2023 #1"},
    {"id": 367, "label": "Hive Series A 2023 #3"},
]
