from datetime import datetime
from unittest.mock import patch

import pytest
from django.conf import settings
from django.urls import reverse

from cashflow.cashcalls.fakers.faker_kyc import KYCFaker
from core_auth.models.user import CustomUser
from core_management.fakers.faker_account import UserFaker
from core_management.fakers.faker_relationships import UserInvestorRelationshipFaker
from core_management.fakers.fakers import FundraisingFaker
from core_management.fakers.fakers import InvestorFaker
from core_management.models import KYC
from core_management.models import Country
from core_management.models import Fundraising
from dealflow.fundraising.fakers.faker_fundraising import FundraisingWithSADocumentFaker
from dealflow.fundraising.models.model_choices import FundraisingStatusChoices
from dealflow.investment.faker_investment import InvestmentWithDocumentFaker
from dealflow.investment.models.models import Investment
from dealflow.investment.models.models_choices import DocumentStatusChoices
from dealflow.investment.models.models_choices import InvestmentStatusChoices
from docusign.models import RequestLogs
from entities.investor.choices import KYCStatusChoices
from entities.investor.models.models import Investor
from entities.startup.models.models import Startup
from entities.startup.tests.fakers.faker_startup import StartupFaker
from ort_files.documentbuilder.result_saver import ResultSaverSubFundraisingSATemplate


test_data: dict = {
    "v": 1,
    "matches_filters": {"current": [1]},
    "meta": {
        "action": "updated",
        "change_source": "app",
        "company_id": 12175019,
        "host": "oneragtimeinvestors-sandbox.pipedrive.com",
        "id": 13845,
        "is_bulk_update": False,
        "matches_filters": {"current": [1]},
        "object": "deal",
        "permitted_user_ids": [17557976, 17611667],
        "pipedrive_service_name": False,
        "timestamp": 1696944265,
        "timestamp_micro": 1696944265300017,
        "prepublish_timestamp": 1696944265472,
        "trans_pending": False,
        "user_id": 17557976,
        "v": 1,
        "webhook_id": "2620860",
    },
    "current": {
        "email_messages_count": 0,
        "cc_email": "oneragtimeinvestors-sandbox+deal13845@pipedrivemail.com",
        "5bdf85cbab2f8630cad1a962d6ba420e26db83f8": "1",
        "products_count": 0,
        "next_activity_date": None,
        "next_activity_type": None,
        "next_activity_duration": None,
        "id": 13845,
        "person_id": 25640,
        "creator_user_id": 17557976,
        "expected_close_date": None,
        "owner_name": "Investor Team",
        "participants_count": 1,
        "stage_id": 5,
        "probability": None,
        "undone_activities_count": 0,
        "active": True,
        "person_name": "Sebastian Testing account",
        "last_activity_date": None,
        "close_time": None,
        "org_hidden": False,
        "next_activity_id": None,
        "weighted_value_currency": "EUR",
        "b184a4616a39b675c78ea5644a7374be150db0a1": "https://core.oneragtime.com/investors/2090",
        "stage_order_nr": 2,
        "next_activity_subject": None,
        "rotten_time": None,
        "user_id": 17557976,
        "visible_to": "3",
        "org_id": 21194,
        "notes_count": 3,
        "next_activity_time": None,
        "formatted_value": "€111",
        "status": "open",
        "formatted_weighted_value": "€111",
        "first_won_time": "2023-10-05 10:13:59",
        "last_outgoing_mail_time": None,
        "b6923458151406bf97a3f694a051f063f6d3506b": "335",
        "title": "April Ali deal",
        "last_activity_id": None,
        "update_time": "2023-10-10 13:24:25",
        "activities_count": 0,
        "pipeline_id": 2,
        "lost_time": None,
        "currency": "EUR",
        "weighted_value": 111,
        "org_name": "Sebas ORG",
        "value": 111,
        "person_hidden": False,
        "next_activity_note": None,
        "files_count": 0,
        "last_incoming_mail_time": None,
        "label": None,
        "lost_reason": None,
        "deleted": False,
        "won_time": None,
        "followers_count": 1,
        "stage_change_time": "2023-10-10 13:24:25",
        "add_time": "2023-10-05 10:13:15",
        "done_activities_count": 0,
    },
    "previous": {
        "email_messages_count": 0,
        "cc_email": "oneragtimeinvestors-sandbox+deal13845@pipedrivemail.com",
        "5bdf85cbab2f8630cad1a962d6ba420e26db83f8": "1",
        "products_count": 0,
        "next_activity_date": None,
        "next_activity_type": None,
        "next_activity_duration": None,
        "id": 13851,
        "person_id": 20257,
        "creator_user_id": 17557976,
        "expected_close_date": None,
        "owner_name": "Investor Team",
        "participants_count": 1,
        "stage_id": 4,
        "probability": None,
        "undone_activities_count": 0,
        "active": True,
        "person_name": "Sebas Golijow",
        "last_activity_date": None,
        "close_time": None,
        "org_hidden": False,
        "next_activity_id": None,
        "weighted_value_currency": "EUR",
        "b184a4616a39b675c78ea5644a7374be150db0a1": "https://core.oneragtime.com/investors/2090",
        "stage_order_nr": 1,
        "next_activity_subject": None,
        "rotten_time": None,
        "user_id": 17557976,
        "visible_to": "3",
        "org_id": 21194,
        "notes_count": 3,
        "next_activity_time": None,
        "formatted_value": "€111",
        "status": "open",
        "formatted_weighted_value": "€111",
        "first_won_time": "2023-10-05 10:13:59",
        "last_outgoing_mail_time": None,
        "b6923458151406bf97a3f694a051f063f6d3506b": "335",
        "title": "April Ali deal",
        "last_activity_id": None,
        "update_time": "2023-10-10 13:23:34",
        "activities_count": 0,
        "pipeline_id": 1,
        "lost_time": None,
        "currency": "EUR",
        "weighted_value": 111,
        "org_name": "April Ali",
        "value": 111,
        "person_hidden": False,
        "next_activity_note": None,
        "files_count": 0,
        "last_incoming_mail_time": None,
        "label": None,
        "lost_reason": None,
        "deleted": False,
        "won_time": None,
        "followers_count": 1,
        "stage_change_time": "2023-10-10 13:23:34",
        "add_time": "2023-10-05 10:13:15",
        "done_activities_count": 0,
    },
    "event": "updated.deal",
    "retry": 0,
}
test_data_2: dict = {
    "v": 1,
    "matches_filters": {"current": [1]},
    "meta": {
        "action": "added",
        "change_source": "app",
        "company_id": 12175019,
        "host": "oneragtimeinvestors-sandbox.pipedrive.com",
        "id": 9525,
        "is_bulk_update": False,
        "matches_filters": {"current": [1]},
        "object": "deal",
        "permitted_user_ids": [17557976, 17611667],
        "pipedrive_service_name": False,
        "timestamp": 1693211100,
        "timestamp_micro": 1693211100219954,
        "prepublish_timestamp": 1693211100659,
        "trans_pending": False,
        "user_id": 17557976,
        "v": 1,
        "webhook_id": "2427070",
    },
    "current": {
        "email_messages_count": 0,
        "cc_email": "oneragtimeinvestors-sandbox+deal9525@pipedrivemail.com",
        "products_count": 0,
        "next_activity_date": None,
        "next_activity_type": None,
        "next_activity_duration": None,
        "id": 9525,
        "person_id": 25640,
        "creator_user_id": 17557976,
        "expected_close_date": None,
        "owner_name": "Investor Team",
        "participants_count": 0,
        "stage_id": 6,
        "probability": None,
        "undone_activities_count": 0,
        "active": True,
        "person_name": "Sebastian Testing account",
        "last_activity_date": None,
        "close_time": None,
        "org_hidden": False,
        "next_activity_id": None,
        "weighted_value_currency": "USD",
        "stage_order_nr": 1,
        "next_activity_subject": None,
        "rotten_time": None,
        "user_id": 17557976,
        "visible_to": "3",
        "org_id": 24332,
        "notes_count": 0,
        "next_activity_time": None,
        "formatted_value": "$1,000",
        "status": "open",
        "formatted_weighted_value": "$1,000",
        "first_won_time": None,
        "last_outgoing_mail_time": None,
        "b6923458151406bf97a3f694a051f063f6d3506b": "16",
        "title": "Sebas ORG deal",
        "last_activity_id": None,
        "update_time": "2023-08-28 08:25:00",
        "activities_count": 0,
        "pipeline_id": 2,
        "lost_time": None,
        "currency": "USD",
        "weighted_value": 1000,
        "org_name": "Sebas ORG",
        "value": 1000,
        "person_hidden": False,
        "next_activity_note": None,
        "files_count": 0,
        "last_incoming_mail_time": None,
        "label": None,
        "lost_reason": None,
        "deleted": False,
        "won_time": None,
        "followers_count": 0,
        "stage_change_time": None,
        "add_time": "2023-08-28 08:25:00",
        "done_activities_count": 0,
    },
    "previous": {
        "email_messages_count": 0,
        "cc_email": "oneragtimeinvestors-sandbox+deal13845@pipedrivemail.com",
        "5bdf85cbab2f8630cad1a962d6ba420e26db83f8": "1",
        "products_count": 0,
        "next_activity_date": None,
        "next_activity_type": None,
        "next_activity_duration": None,
        "id": 13851,
        "person_id": 20257,
        "creator_user_id": 17557976,
        "expected_close_date": None,
        "owner_name": "Investor Team",
        "participants_count": 1,
        "stage_id": 5,
        "probability": None,
        "undone_activities_count": 0,
        "active": True,
        "person_name": "Sebas Golijow",
        "last_activity_date": None,
        "close_time": None,
        "org_hidden": False,
        "next_activity_id": None,
        "weighted_value_currency": "EUR",
        "b184a4616a39b675c78ea5644a7374be150db0a1": "https://core.oneragtime.com/investors/2090",
        "stage_order_nr": 1,
        "next_activity_subject": None,
        "rotten_time": None,
        "user_id": 17557976,
        "visible_to": "3",
        "org_id": 21194,
        "notes_count": 3,
        "next_activity_time": None,
        "formatted_value": "€111",
        "status": "open",
        "formatted_weighted_value": "€111",
        "first_won_time": "2023-10-05 10:13:59",
        "last_outgoing_mail_time": None,
        "b6923458151406bf97a3f694a051f063f6d3506b": "335",
        "title": "April Ali deal",
        "last_activity_id": None,
        "update_time": "2023-10-10 13:23:34",
        "activities_count": 0,
        "pipeline_id": 1,
        "lost_time": None,
        "currency": "EUR",
        "weighted_value": 111,
        "org_name": "April Ali",
        "value": 111,
        "person_hidden": False,
        "next_activity_note": None,
        "files_count": 0,
        "last_incoming_mail_time": None,
        "label": None,
        "lost_reason": None,
        "deleted": False,
        "won_time": None,
        "followers_count": 1,
        "stage_change_time": "2023-10-10 13:23:34",
        "add_time": "2023-10-05 10:13:15",
        "done_activities_count": 0,
    },
    "event": "added.deal",
    "retry": 0,
}
test_data_4: dict = {
    "v": 1,
    "matches_filters": {"current": [1]},
    "meta": {
        "action": "added",
        "change_source": "app",
        "company_id": 12175019,
        "host": "oneragtimeinvestors-sandbox.pipedrive.com",
        "id": 9525,
        "is_bulk_update": False,
        "matches_filters": {"current": [1]},
        "object": "deal",
        "permitted_user_ids": [17557976, 17611667],
        "pipedrive_service_name": False,
        "timestamp": 1693211100,
        "timestamp_micro": 1693211100219954,
        "prepublish_timestamp": 1693211100659,
        "trans_pending": False,
        "user_id": 17557976,
        "v": 1,
        "webhook_id": "2427070",
    },
    "current": {
        "email_messages_count": 0,
        "cc_email": "oneragtimeinvestors-sandbox+deal9525@pipedrivemail.com",
        "products_count": 0,
        "next_activity_date": None,
        "next_activity_type": None,
        "next_activity_duration": None,
        "id": 9525,
        "person_id": 15958,
        "creator_user_id": 17557976,
        "expected_close_date": None,
        "owner_name": "Investor Team",
        "participants_count": 0,
        "stage_id": 7,
        "probability": None,
        "undone_activities_count": 0,
        "active": True,
        "person_name": None,
        "last_activity_date": None,
        "close_time": None,
        "org_hidden": False,
        "next_activity_id": None,
        "weighted_value_currency": "USD",
        "stage_order_nr": 1,
        "next_activity_subject": None,
        "rotten_time": None,
        "user_id": 17557976,
        "visible_to": "3",
        "org_id": None,
        "notes_count": 0,
        "next_activity_time": None,
        "formatted_value": "$1,000",
        "status": "open",
        "formatted_weighted_value": "$1,000",
        "first_won_time": None,
        "last_outgoing_mail_time": None,
        "b6923458151406bf97a3f694a051f063f6d3506b": "16",
        "title": "Sebas ORG deal",
        "last_activity_id": None,
        "update_time": "2023-08-28 08:25:00",
        "activities_count": 0,
        "pipeline_id": 2,
        "lost_time": None,
        "currency": "USD",
        "weighted_value": 1000,
        "org_name": "Sebas ORG",
        "value": 1000,
        "person_hidden": False,
        "next_activity_note": None,
        "files_count": 0,
        "last_incoming_mail_time": None,
        "label": None,
        "lost_reason": None,
        "deleted": False,
        "won_time": None,
        "followers_count": 0,
        "stage_change_time": None,
        "add_time": "2023-08-28 08:25:00",
        "done_activities_count": 0,
    },
    "previous": None,
    "event": "added.deal",
    "retry": 0,
}
test_data_5: dict = {
    "v": 1,
    "matches_filters": {"current": [1]},
    "meta": {
        "action": "added",
        "change_source": "app",
        "company_id": 12175019,
        "host": "oneragtimeinvestors-sandbox.pipedrive.com",
        "id": 9525,
        "is_bulk_update": False,
        "matches_filters": {"current": [1]},
        "object": "deal",
        "permitted_user_ids": [17557976, 17611667],
        "pipedrive_service_name": False,
        "timestamp": 1693211100,
        "timestamp_micro": 1693211100219954,
        "prepublish_timestamp": 1693211100659,
        "trans_pending": False,
        "user_id": 17557976,
        "v": 1,
        "webhook_id": "2427070",
    },
    "current": {
        "email_messages_count": 0,
        "cc_email": "oneragtimeinvestors-sandbox+deal9525@pipedrivemail.com",
        "products_count": 0,
        "next_activity_date": None,
        "next_activity_type": None,
        "next_activity_duration": None,
        "id": 9525,
        "person_id": 15958,
        "creator_user_id": 17557976,
        "expected_close_date": None,
        "owner_name": "Investor Team",
        "participants_count": 0,
        "stage_id": 3,
        "probability": None,
        "undone_activities_count": 0,
        "active": True,
        "person_name": "Sebas Golijow",
        "last_activity_date": None,
        "close_time": None,
        "org_hidden": False,
        "next_activity_id": None,
        "weighted_value_currency": "USD",
        "stage_order_nr": 1,
        "next_activity_subject": None,
        "rotten_time": None,
        "user_id": 17557976,
        "visible_to": "3",
        "org_id": 13912,
        "notes_count": 0,
        "next_activity_time": None,
        "formatted_value": "$1,000",
        "status": "open",
        "formatted_weighted_value": "$1,000",
        "first_won_time": None,
        "last_outgoing_mail_time": None,
        "b6923458151406bf97a3f694a051f063f6d3506b": "16",
        "title": "Sebas ORG deal",
        "last_activity_id": None,
        "update_time": "2023-08-28 08:25:00",
        "activities_count": 0,
        "pipeline_id": 1,
        "lost_time": None,
        "currency": "USD",
        "weighted_value": 1000,
        "org_name": "Sebas ORG",
        "value": 1000,
        "person_hidden": False,
        "next_activity_note": None,
        "files_count": 0,
        "last_incoming_mail_time": None,
        "label": None,
        "lost_reason": None,
        "deleted": False,
        "won_time": None,
        "followers_count": 0,
        "stage_change_time": None,
        "add_time": "2023-08-28 08:25:00",
        "done_activities_count": 0,
    },
    "previous": None,
    "event": "added.deal",
    "retry": 0,
}
test_data_1: dict = {
    "v": 1,
    "matches_filters": {"current": [1]},
    "meta": {
        "action": "updated",
        "change_source": "app",
        "company_id": 12175019,
        "host": "oneragtimeinvestors-sandbox.pipedrive.com",
        "id": 9526,
        "is_bulk_update": False,
        "matches_filters": {"current": [1]},
        "object": "deal",
        "permitted_user_ids": [17557976, 17611667],
        "pipedrive_service_name": False,
        "timestamp": 1693485777,
        "timestamp_micro": 1693485777197050,
        "prepublish_timestamp": 1693485777372,
        "trans_pending": False,
        "user_id": 17557976,
        "v": 1,
        "webhook_id": "2435470",
    },
    "current": {
        "email_messages_count": 0,
        "cc_email": "oneragtimeinvestors-sandbox+deal9526@pipedrivemail.com",
        "products_count": 0,
        "next_activity_date": None,
        "next_activity_type": None,
        "next_activity_duration": None,
        "id": 9526,
        "person_id": 15292,
        "creator_user_id": 17557976,
        "expected_close_date": None,
        "owner_name": "Investor Team",
        "participants_count": 1,
        "stage_id": 5,
        "probability": None,
        "undone_activities_count": 0,
        "active": True,
        "person_name": "Sebas golijow",
        "last_activity_date": None,
        "close_time": None,
        "org_hidden": False,
        "next_activity_id": None,
        "weighted_value_currency": "USD",
        "b184a4616a39b675c78ea5644a7374be150db0a1": None,
        "stage_order_nr": 4,
        "next_activity_subject": None,
        "rotten_time": None,
        "user_id": 17557976,
        "visible_to": "3",
        "org_id": 15075,
        "notes_count": 0,
        "next_activity_time": None,
        "formatted_value": "$1,000",
        "status": "open",
        "formatted_weighted_value": "$1,000",
        "first_won_time": None,
        "last_outgoing_mail_time": None,
        "b6923458151406bf97a3f694a051f063f6d3506b": "16",
        "title": "Jonathan Robinson deal",
        "last_activity_id": None,
        "update_time": "2023-08-31 12:42:57",
        "activities_count": 0,
        "pipeline_id": 2,
        "lost_time": None,
        "currency": "USD",
        "weighted_value": 1000,
        "org_name": "Jonathan Robinson",
        "value": None,
        "person_hidden": False,
        "next_activity_note": None,
        "files_count": 0,
        "last_incoming_mail_time": None,
        "label": None,
        "lost_reason": None,
        "deleted": False,
        "won_time": None,
        "followers_count": 1,
        "stage_change_time": "2023-08-31 12:42:57",
        "add_time": "2023-08-28 08:31:35",
        "done_activities_count": 0,
    },
    "previous": {
        "email_messages_count": 0,
        "cc_email": "oneragtimeinvestors-sandbox+deal9526@pipedrivemail.com",
        "products_count": 0,
        "next_activity_date": None,
        "next_activity_type": None,
        "next_activity_duration": None,
        "id": 9526,
        "person_id": 15292,
        "creator_user_id": 17557976,
        "expected_close_date": None,
        "owner_name": "Investor Team",
        "participants_count": 1,
        "stage_id": 4,
        "probability": None,
        "undone_activities_count": 0,
        "active": True,
        "person_name": "Seba golijow",
        "last_activity_date": None,
        "close_time": None,
        "org_hidden": False,
        "next_activity_id": None,
        "weighted_value_currency": "USD",
        "b184a4616a39b675c78ea5644a7374be150db0a1": None,
        "stage_order_nr": 2,
        "next_activity_subject": None,
        "rotten_time": None,
        "user_id": 17557976,
        "visible_to": "3",
        "org_id": None,
        "notes_count": 0,
        "next_activity_time": None,
        "formatted_value": "$1,000",
        "status": "open",
        "formatted_weighted_value": "$1,000",
        "first_won_time": None,
        "last_outgoing_mail_time": None,
        "b6923458151406bf97a3f694a051f063f6d3506b": None,
        "title": "Jonathan Robinson deal",
        "last_activity_id": None,
        "update_time": "2023-08-31 12:41:04",
        "activities_count": 0,
        "pipeline_id": 2,
        "lost_time": None,
        "currency": "USD",
        "weighted_value": 1000,
        "org_name": "Jonathan Robinson",
        "value": 1000,
        "person_hidden": False,
        "next_activity_note": None,
        "files_count": 0,
        "last_incoming_mail_time": None,
        "label": None,
        "lost_reason": None,
        "deleted": False,
        "won_time": None,
        "followers_count": 1,
        "stage_change_time": "2023-08-31 12:41:04",
        "add_time": "2023-08-28 08:31:35",
        "done_activities_count": 0,
    },
    "event": "updated.deal",
    "retry": 0,
}
test_data_initial_validation: dict = {
    "v": 1,
    "matches_filters": {"current": [1]},
    "meta": {
        "action": "updated",
        "change_source": "app",
        "company_id": 12175019,
        "host": "oneragtimeinvestors-sandbox.pipedrive.com",
        "id": 13845,
        "is_bulk_update": False,
        "matches_filters": {"current": [1]},
        "object": "deal",
        "permitted_user_ids": [17557976, 17611667],
        "pipedrive_service_name": False,
        "timestamp": 1696944265,
        "timestamp_micro": 1696944265300017,
        "prepublish_timestamp": 1696944265472,
        "trans_pending": False,
        "user_id": 17557976,
        "v": 1,
        "webhook_id": "2620860",
    },
    "current": {
        "email_messages_count": 0,
        "cc_email": "oneragtimeinvestors-sandbox+deal13845@pipedrivemail.com",
        "5bdf85cbab2f8630cad1a962d6ba420e26db83f8": "1",
        "products_count": 0,
        "next_activity_date": None,
        "next_activity_type": None,
        "next_activity_duration": None,
        "id": 13845,
        "person_id": 23059,
        "creator_user_id": 17557976,
        "expected_close_date": None,
        "owner_name": "Investor Team",
        "participants_count": 1,
        "stage_id": 5,
        "probability": None,
        "undone_activities_count": 0,
        "active": True,
        "person_name": "Test Validation",
        "last_activity_date": None,
        "close_time": None,
        "org_hidden": False,
        "next_activity_id": None,
        "weighted_value_currency": "EUR",
        "b184a4616a39b675c78ea5644a7374be150db0a1": "https://core.oneragtime.com/investors/2090",
        "stage_order_nr": 2,
        "next_activity_subject": None,
        "rotten_time": None,
        "user_id": 17557976,
        "visible_to": "3",
        "org_id": 23121,
        "notes_count": 3,
        "next_activity_time": None,
        "formatted_value": "€111",
        "status": "open",
        "formatted_weighted_value": "€111",
        "first_won_time": "2023-10-05 10:13:59",
        "last_outgoing_mail_time": None,
        "b6923458151406bf97a3f694a051f063f6d3506b": "335",
        "title": "April Ali deal",
        "last_activity_id": None,
        "update_time": "2023-10-10 13:24:25",
        "activities_count": 0,
        "pipeline_id": 2,
        "lost_time": None,
        "currency": "EUR",
        "weighted_value": 111,
        "org_name": "Sebas ORG",
        "value": 111,
        "person_hidden": False,
        "next_activity_note": None,
        "files_count": 0,
        "last_incoming_mail_time": None,
        "label": None,
        "lost_reason": None,
        "deleted": False,
        "won_time": None,
        "followers_count": 1,
        "stage_change_time": "2023-10-10 13:24:25",
        "add_time": "2023-10-05 10:13:15",
        "done_activities_count": 0,
    },
    "previous": {
        "email_messages_count": 0,
        "cc_email": "oneragtimeinvestors-sandbox+deal13845@pipedrivemail.com",
        "5bdf85cbab2f8630cad1a962d6ba420e26db83f8": "1",
        "products_count": 0,
        "next_activity_date": None,
        "next_activity_type": None,
        "next_activity_duration": None,
        "id": 13851,
        "person_id": 21986,
        "creator_user_id": 17557976,
        "expected_close_date": None,
        "owner_name": "Investor Team",
        "participants_count": 1,
        "stage_id": 4,
        "probability": None,
        "undone_activities_count": 0,
        "active": True,
        "person_name": "Sebas Golijow",
        "last_activity_date": None,
        "close_time": None,
        "org_hidden": False,
        "next_activity_id": None,
        "weighted_value_currency": "EUR",
        "b184a4616a39b675c78ea5644a7374be150db0a1": "https://core.oneragtime.com/investors/2090",
        "stage_order_nr": 1,
        "next_activity_subject": None,
        "rotten_time": None,
        "user_id": 17557976,
        "visible_to": "3",
        "org_id": 21194,
        "notes_count": 3,
        "next_activity_time": None,
        "formatted_value": "€111",
        "status": "open",
        "formatted_weighted_value": "€111",
        "first_won_time": "2023-10-05 10:13:59",
        "last_outgoing_mail_time": None,
        "b6923458151406bf97a3f694a051f063f6d3506b": "335",
        "title": "April Ali deal",
        "last_activity_id": None,
        "update_time": "2023-10-10 13:23:34",
        "activities_count": 0,
        "pipeline_id": 1,
        "lost_time": None,
        "currency": "EUR",
        "weighted_value": 111,
        "org_name": "April Ali",
        "value": 111,
        "person_hidden": False,
        "next_activity_note": None,
        "files_count": 0,
        "last_incoming_mail_time": None,
        "label": None,
        "lost_reason": None,
        "deleted": False,
        "won_time": None,
        "followers_count": 1,
        "stage_change_time": "2023-10-10 13:23:34",
        "add_time": "2023-10-05 10:13:15",
        "done_activities_count": 0,
    },
    "event": "updated.deal",
    "retry": 0,
}
test_data_no_action_needed: dict = {
    "v": 1,
    "matches_filters": {"current": [1]},
    "meta": {
        "action": "updated",
        "change_source": "app",
        "company_id": 12175019,
        "host": "oneragtimeinvestors-sandbox.pipedrive.com",
        "id": 13862,
        "is_bulk_update": False,
        "matches_filters": {"current": [1]},
        "object": "deal",
        "permitted_user_ids": [17557976, 17611667],
        "pipedrive_service_name": False,
        "timestamp": 1697707907,
        "timestamp_micro": 1697707907027006,
        "prepublish_timestamp": 1697707907242,
        "trans_pending": False,
        "user_id": 17557976,
        "v": 1,
        "webhook_id": "2698679",
    },
    "current": {
        "email_messages_count": 0,
        "cc_email": "oneragtimeinvestors-sandbox+deal13862@pipedrivemail.com",
        "5bdf85cbab2f8630cad1a962d6ba420e26db83f8": None,
        "products_count": 0,
        "next_activity_date": None,
        "next_activity_type": None,
        "next_activity_duration": None,
        "id": 13862,
        "person_id": 25640,
        "creator_user_id": 17557976,
        "expected_close_date": None,
        "owner_name": "Investor Team",
        "participants_count": 1,
        "stage_id": 4,
        "probability": None,
        "undone_activities_count": 0,
        "active": True,
        "person_name": "Sebastian Testing account",
        "last_activity_date": None,
        "close_time": None,
        "org_hidden": False,
        "next_activity_id": None,
        "weighted_value_currency": "EUR",
        "b184a4616a39b675c78ea5644a7374be150db0a1": None,
        "stage_order_nr": 1,
        "next_activity_subject": None,
        "rotten_time": None,
        "user_id": 17557976,
        "visible_to": "3",
        "org_id": 23325,
        "notes_count": 0,
        "next_activity_time": None,
        "formatted_value": "€1",
        "status": "open",
        "formatted_weighted_value": "€1",
        "first_won_time": None,
        "last_outgoing_mail_time": None,
        "b6923458151406bf97a3f694a051f063f6d3506b": "335",
        "title": "Aston Villa deal",
        "last_activity_id": None,
        "update_time": "2023-10-19 09:31:47",
        "activities_count": 0,
        "pipeline_id": 1,
        "lost_time": None,
        "currency": "EUR",
        "weighted_value": 1,
        "org_name": "Aston Villa",
        "value": 1,
        "person_hidden": False,
        "next_activity_note": None,
        "files_count": 0,
        "last_incoming_mail_time": None,
        "label": None,
        "lost_reason": None,
        "deleted": False,
        "won_time": None,
        "followers_count": 1,
        "stage_change_time": "2023-10-19 09:31:47",
        "add_time": "2023-10-19 09:16:11",
        "done_activities_count": 0,
    },
    "previous": {
        "email_messages_count": 0,
        "cc_email": "oneragtimeinvestors-sandbox+deal13862@pipedrivemail.com",
        "5bdf85cbab2f8630cad1a962d6ba420e26db83f8": None,
        "products_count": 0,
        "next_activity_date": None,
        "next_activity_type": None,
        "next_activity_duration": None,
        "id": 13862,
        "person_id": 22189,
        "creator_user_id": 17557976,
        "expected_close_date": None,
        "owner_name": "Investor Team",
        "participants_count": 1,
        "stage_id": 3,
        "probability": None,
        "undone_activities_count": 0,
        "active": True,
        "person_name": "Emi Martinez",
        "last_activity_date": None,
        "close_time": None,
        "org_hidden": False,
        "next_activity_id": None,
        "weighted_value_currency": "EUR",
        "b184a4616a39b675c78ea5644a7374be150db0a1": None,
        "stage_order_nr": 0,
        "next_activity_subject": None,
        "rotten_time": None,
        "user_id": 17557976,
        "visible_to": "3",
        "org_id": 23325,
        "notes_count": 0,
        "next_activity_time": None,
        "formatted_value": "€1",
        "status": "open",
        "formatted_weighted_value": "€1",
        "first_won_time": None,
        "last_outgoing_mail_time": None,
        "b6923458151406bf97a3f694a051f063f6d3506b": "420",
        "title": "Aston Villa deal",
        "last_activity_id": None,
        "update_time": "2023-10-19 09:31:38",
        "activities_count": 0,
        "pipeline_id": 1,
        "lost_time": None,
        "currency": "EUR",
        "weighted_value": 1,
        "org_name": "Aston Villa",
        "value": 1,
        "person_hidden": False,
        "next_activity_note": None,
        "files_count": 0,
        "last_incoming_mail_time": None,
        "label": None,
        "lost_reason": None,
        "deleted": False,
        "won_time": None,
        "followers_count": 1,
        "stage_change_time": "2023-10-19 09:31:38",
        "add_time": "2023-10-19 09:16:11",
        "done_activities_count": 0,
    },
    "event": "updated.deal",
    "retry": 0,
}


@pytest.mark.django_db
class TestDealWebhook:
    def url(self) -> str:
        return reverse("api:pipedrive-investors-webhook")

    def test_url(self):
        assert "/api/v2/pipedrive-sdk/investors/" == self.url()

    @patch("services.email.sendinblue_mail.SendInBlueMail.send")
    def test_view_case_no_user_no_investor(self, send, client):
        users_count: int = CustomUser.objects.count()
        investor_count: int = Investor.objects.count()
        startup: Startup = StartupFaker(name="test")
        FundraisingFaker(name="Keli Network Seed 2017 #3", startup=startup)
        response = client.post(self.url(), test_data, format="json")
        assert response.json() == "Entities successfully created"
        assert (
            CustomUser.objects.last().acccount_management_relationship.relationship_id
            != None
        )
        assert (
            CustomUser.objects.last().acccount_management_relationship.entity_type
            != None
        )
        assert CustomUser.objects.last().settings.preferred_language != None
        assert CustomUser.objects.last().contact_info.first_name != None
        assert CustomUser.objects.last().contact_info.signup_date != None
        assert CustomUser.objects.count() == users_count + 1
        assert Investor.objects.count() == investor_count + 1
        send.assert_called

    @patch("services.email.sendinblue_mail.SendInBlueMail.send")
    def test_view_user_and_investor_exists_kyc_not_validated(self, send, client):
        users_count: int = CustomUser.objects.count()
        investor_count: int = Investor.objects.count()
        user = UserFaker(
            first_name="Sebas",
            last_name="Testing account",
            email="sebastiantesting@account.com",
        )
        investor = InvestorFaker(
            name="Sebas ORG",
            kyc=KYCFaker(
                email="sebastiantesting@account.com",
                status=KYCStatusChoices.waiting_submit.name,
            ),
        )
        UserInvestorRelationshipFaker(investor=investor, account=user)
        startup: Startup = StartupFaker(name="test")
        FundraisingFaker(name="Keli Network Seed 2017 #3", startup=startup)
        response = client.post(self.url(), test_data, format="json")
        assert (
            response.json()
            == f"[Pipedrive to Core error] <https://www.core.oneragtime.com/investors/{investor.id}|Investor> kyc is not validated"
        )
        users_count == users_count
        investor_count == investor_count
        send.assert_called

    @patch("services.email.sendinblue_mail.SendInBlueMail.send")
    def test_deal_update_create_investment_in_core(self, send, client):
        user = UserFaker(
            email="sebastiantesting@account.com",
            first_name="Sebastian",
            last_name="Testing account",
            onboarded_on=datetime.now(),
        )
        kyc = KYCFaker(
            email="sebastiantesting@account.com",
            birthday=datetime.now(),
            country_of_residence=Country.objects.last(),
            status=KYCStatusChoices.validated.name,
        )
        investor = InvestorFaker(name="Sebas ORG", kyc=kyc)
        UserInvestorRelationshipFaker(account=user, investor=investor)
        startup: Startup = StartupFaker(name="test")
        fundraising = FundraisingFaker(
            name="Sonio Seed",
            startup=startup,
            status=FundraisingStatusChoices.open.name,
        )
        investments_count: int = Investment.objects.count()
        users_count: int = CustomUser.objects.count()
        result_saver = ResultSaverSubFundraisingSATemplate(
            spv="FRENCH",
            language="FR",
            fundraising=fundraising,
        )
        path = (
            settings.PROJECT_DIR + "/ort_files/document/tests/test_files/test_file.docx"
        )
        result_saver.save_document(path)
        response = client.post(self.url(), test_data_2, format="json")
        investment_id = Investment.objects.last().id
        assert (
            response.json()
            == f"[Pipedrive Update] Investment successfully created:  core.oneragtime.com/investments/{investment_id}"
        )
        investment = Investment.objects.last()
        assert Investment.objects.count() == investments_count + 1
        assert CustomUser.objects.count() == users_count
        assert RequestLogs.objects.filter(
            document_entity_type="Investment",
            document_entity_id=investment.id,
        ).exists()
        send.assert_called

    def test_sa_validator_on_create_investment(self, client):
        user = UserFaker(
            email="sebastiantesting@account.com",
            first_name="Sebastian",
            last_name="Testing account",
            onboarded_on=None,
        )
        kyc = KYCFaker(
            email="sebastiantesting@account.com",
            birthday=datetime.now(),
            country_of_residence=Country.objects.last(),
        )
        investor = InvestorFaker(name="Sebas ORG", kyc=kyc)
        UserInvestorRelationshipFaker(account=user, investor=investor)
        startup: Startup = StartupFaker(name="test")
        fundraising = FundraisingFaker(name="Sonio Seed", startup=startup)
        result_saver = ResultSaverSubFundraisingSATemplate(
            spv="FRENCH",
            language="FR",
            fundraising=fundraising,
        )
        path = (
            settings.PROJECT_DIR + "/ort_files/document/tests/test_files/test_file.docx"
        )
        result_saver.save_document(path)
        response = client.post(self.url(), test_data_2, format="json")
        assert (
            response.json()
            == f"[Pipedrive] This Deal was moved to Commited. However, there is an error: [Pipedrive to Core error] <https://www.core.oneragtime.com/users/{user.id}|Sebastian Testing account> is not onboarded, so the Deal has been moved back to potential deal"
        )

    def test_pipedrive_webhook_serializer(self, client):
        user: CustomUser = UserFaker(email="test@updated.com", is_active=True)
        startup: Startup = StartupFaker(name="test")
        fundraising: Fundraising = FundraisingWithSADocumentFaker(
            name="Sonio Seed", startup=startup
        )
        result_saver = ResultSaverSubFundraisingSATemplate(
            spv="FRENCH",
            language="FR",
            fundraising=fundraising,
        )
        path = (
            settings.PROJECT_DIR + "/ort_files/document/tests/test_files/test_file.docx"
        )
        result_saver.save_document(path)
        kyc: KYC = KYCFaker(
            email="test@updated.com", status=KYCStatusChoices.validated.name
        )
        investor: Investor = InvestorFaker(name="Sebas Golijow", kyc=kyc)
        UserInvestorRelationshipFaker(account=user, investor=investor)

        InvestmentWithDocumentFaker(
            investor=investor,
            id=23,
            fundraising=fundraising,
            status=InvestmentStatusChoices.requested.name,
            document_subscription_agreement_status=DocumentStatusChoices.validated.name,
        )
        response = client.post(self.url(), test_data_1, format="json")
        assert (
            response.data
            == "[Pipedrive to Core Error] Missing deal ['value'] in pipedrive deal: https://oneragtimeinvestors.pipedrive.com/deal/9526"
        )

    def test_view_initial_validation(self, client):
        startup: Startup = StartupFaker(name="test")
        FundraisingFaker(name="Keli Network Seed 2017 #3", startup=startup)
        response = client.post(self.url(), test_data_initial_validation, format="json")
        assert (
            response.json()
            == "[Pipedrive to Core Error] Missing deal ['email'] in pipedrive deal: https://oneragtimeinvestors.pipedrive.com/deal/13845"
        )

    def test_view_case_no_action_needed(self, client):
        startup: Startup = StartupFaker(name="test")
        FundraisingFaker(name="Keli Network Seed 2017 #3", startup=startup)
        response = client.post(self.url(), test_data_no_action_needed, format="json")
        assert response.json() == "No action needed"

    @patch("services.email.sendinblue_mail.SendInBlueMail.send")
    def test_deal_update_create_investment_in_core_repetead_kyc(self, send, client):
        user = UserFaker(
            email="sebastiantesting@account.com",
            first_name="Sebastian",
            last_name="Testing account",
            onboarded_on=datetime.now(),
        )
        kyc = KYCFaker(
            email="sebastiantesting@account.com",
            company_name="Test 1",
            birthday=datetime.now(),
            country_of_residence=Country.objects.last(),
            status=KYCStatusChoices.validated.name,
        )
        KYCFaker(
            email="sebastiantesting@account.com",
            company_name="Test 2",
            birthday=datetime.now(),
            country_of_residence=Country.objects.last(),
            status=KYCStatusChoices.validated.name,
        )
        KYCFaker(
            email="sebastiantesting@account.com",
            company_name="Sebas ORG",
            birthday=datetime.now(),
            country_of_residence=Country.objects.last(),
            status=KYCStatusChoices.validated.name,
        )
        investor = InvestorFaker(name="Sebas ORG", kyc=kyc)
        UserInvestorRelationshipFaker(account=user, investor=investor)
        startup: Startup = StartupFaker(name="test")
        fundraising = FundraisingFaker(
            name="Sonio Seed",
            startup=startup,
            status=FundraisingStatusChoices.open.name,
        )
        result_saver = ResultSaverSubFundraisingSATemplate(
            spv="FRENCH",
            language="FR",
            fundraising=fundraising,
        )
        path = (
            settings.PROJECT_DIR + "/ort_files/document/tests/test_files/test_file.docx"
        )
        result_saver.save_document(path)
        response = client.post(self.url(), test_data_2, format="json")
        assert response.status_code == 200
